apiVersion: v1
kind: Secret
metadata:
  name: mysql
type: Opaque
data:
  # The key here is the environment variable name, and the value is base64 encoded
  MYSQL_USER: c2hpcHBpbmcK
  MYSQL_PASSWORD: Um9ib1Nob3BAMQo=

# # Encoding
# echo 'shipping' | base64
# echo 'RoboShop@1' | base64
# # Decoding
# echo '<encode_value>' | base64 --decode

